//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.JAXWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.checkerfacade.cesi.com/", ConfigurationName="JAXWS.CheckerEndpoint")]
    public interface CheckerEndpoint {
        
        // CODEGEN: Generating message contract since element name appToken from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.checkerfacade.cesi.com/CheckerEndpoint/checkDecryptRequest", ReplyAction="http://facade.checkerfacade.cesi.com/CheckerEndpoint/checkDecryptResponse")]
        Client.JAXWS.checkDecryptResponse checkDecrypt(Client.JAXWS.checkDecryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkDecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkDecrypt", Namespace="http://facade.checkerfacade.cesi.com/", Order=0)]
        public Client.JAXWS.checkDecryptRequestBody Body;
        
        public checkDecryptRequest() {
        }
        
        public checkDecryptRequest(Client.JAXWS.checkDecryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkDecryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string decryptInfo;
        
        public checkDecryptRequestBody() {
        }
        
        public checkDecryptRequestBody(string appToken, string decryptInfo) {
            this.appToken = appToken;
            this.decryptInfo = decryptInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkDecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkDecryptResponse", Namespace="http://facade.checkerfacade.cesi.com/", Order=0)]
        public Client.JAXWS.checkDecryptResponseBody Body;
        
        public checkDecryptResponse() {
        }
        
        public checkDecryptResponse(Client.JAXWS.checkDecryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkDecryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string decryptValidation;
        
        public checkDecryptResponseBody() {
        }
        
        public checkDecryptResponseBody(string decryptValidation) {
            this.decryptValidation = decryptValidation;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckerEndpointChannel : Client.JAXWS.CheckerEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckerEndpointClient : System.ServiceModel.ClientBase<Client.JAXWS.CheckerEndpoint>, Client.JAXWS.CheckerEndpoint {
        
        public CheckerEndpointClient() {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckerEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.JAXWS.checkDecryptResponse Client.JAXWS.CheckerEndpoint.checkDecrypt(Client.JAXWS.checkDecryptRequest request) {
            return base.Channel.checkDecrypt(request);
        }
        
        public string checkDecrypt(string appToken, string decryptInfo) {
            Client.JAXWS.checkDecryptRequest inValue = new Client.JAXWS.checkDecryptRequest();
            inValue.Body = new Client.JAXWS.checkDecryptRequestBody();
            inValue.Body.appToken = appToken;
            inValue.Body.decryptInfo = decryptInfo;
            Client.JAXWS.checkDecryptResponse retVal = ((Client.JAXWS.CheckerEndpoint)(this)).checkDecrypt(inValue);
            return retVal.Body.decryptValidation;
        }
    }
}
